import { TourPackage, Vehicle, Review } from './types';
import { fourDayNamibiaItinerary, sevenDayNamibiaItinerary, southernAfricaTour } from './itineraryData';

export const mockTours: TourPackage[] = [
  {
    id: '1',
    title: 'Namibian Highlights Tour',
    description: 'Experience the best of Namibia with our most popular 10-day tour package. Visit Sossusvlei, Swakopmund, and Etosha National Park.',
    price: 1899,
    duration: 10,
    image: '/images/sossusvlei.jpg',
    featured: true,
    attractions: ['Sossusvlei', 'Swakopmund', 'Etosha National Park', 'Windhoek'],
    inclusions: ['Accommodation', 'Transportation', 'Guide', 'Most meals', 'Park entrance fees'],
    exclusions: ['International flights', 'Travel insurance', 'Personal expenses'],
    created_at: '2024-01-15T00:00:00Z',
    itinerary: sevenDayNamibiaItinerary
  },
  {
    id: '2',
    title: 'Etosha Wildlife Safari',
    description: 'Discover the incredible wildlife of Namibia with our 7-day safari package focused on Etosha National Park.',
    price: 1299,
    duration: 7,
    image: '/images/etosha-wildlife.jpg',
    featured: true,
    attractions: ['Etosha National Park', 'Okonjima Nature Reserve', 'Windhoek'],
    inclusions: ['Safari lodges', '4x4 Game drives', 'Professional guide', 'All meals', 'Park entrance fees'],
    exclusions: ['International flights', 'Travel insurance', 'Personal expenses'],
    created_at: '2024-01-20T00:00:00Z',
    itinerary: sevenDayNamibiaItinerary
  },
  {
    id: '3',
    title: 'Desert Explorer',
    description: 'Experience the stunning Namib Desert, including the famous red dunes of Sossusvlei and the eerie Deadvlei.',
    price: 1199,
    duration: 5,
    image: '/images/namibia-desert.jpg',
    featured: false,
    attractions: ['Sossusvlei', 'Deadvlei', 'Sesriem Canyon', 'Namib-Naukluft National Park'],
    inclusions: ['Desert lodges', 'Transportation', 'Guide', 'Most meals', 'Park entrance fees'],
    exclusions: ['International flights', 'Travel insurance', 'Personal expenses'],
    created_at: '2024-02-01T00:00:00Z',
    itinerary: fourDayNamibiaItinerary
  },
  {
    id: '4',
    title: 'Coastal Adventure',
    description: 'Explore the fascinating Atlantic coastline of Namibia, including Swakopmund, Walvis Bay, and the Skeleton Coast.',
    price: 1499,
    duration: 6,
    image: '/images/skeleton-coast.jpg',
    featured: false,
    attractions: ['Swakopmund', 'Walvis Bay', 'Skeleton Coast', 'Cape Cross Seal Colony'],
    inclusions: ['Accommodation', 'Transportation', 'Guide', 'Most meals', 'Activities'],
    exclusions: ['International flights', 'Travel insurance', 'Personal expenses'],
    created_at: '2024-02-10T00:00:00Z',
    itinerary: southernAfricaTour
  },
  {
    id: '5',
    title: 'Cultural Experience',
    description: 'Immerse yourself in the rich cultures of Namibia, including visits to Himba and San communities.',
    price: 1599,
    duration: 8,
    image: '/images/namibia-culture.jpg',
    featured: true,
    attractions: ['Himba Village', 'San Community', 'Twyfelfontein Rock Engravings', 'Damaraland'],
    inclusions: ['Cultural lodges', 'Transportation', 'Cultural guide', 'All meals', 'Community contributions'],
    exclusions: ['International flights', 'Travel insurance', 'Personal expenses'],
    created_at: '2024-02-15T00:00:00Z',
    itinerary: southernAfricaTour
  },
  {
    id: '6',
    title: 'Fish River Canyon Trek',
    description: 'Challenge yourself with a trek through the stunning Fish River Canyon, the second largest canyon in the world.',
    price: 1799,
    duration: 9,
    image: '/images/fish-river-canyon.jpg',
    featured: false,
    attractions: ['Fish River Canyon', 'Ai-Ais Hot Springs', 'Quiver Tree Forest'],
    inclusions: ['Camping equipment', 'Guide', 'All meals during trek', 'Support vehicle'],
    exclusions: ['International flights', 'Travel insurance', 'Personal expenses'],
    created_at: '2024-02-20T00:00:00Z',
    itinerary: southernAfricaTour
  },
  {
    id: '7',
    title: 'Namibia 7-Day Classic Tour',
    description: 'Discover the highlights of Namibia with this comprehensive 7-day tour including Windhoek, Sossusvlei, and Swakopmund.',
    price: 1599,
    duration: 7,
    image: '/images/namibia-classic.jpg',
    featured: true,
    attractions: ['Windhoek', 'Sossusvlei', 'Deadvlei', 'Swakopmund', 'Sesriem Canyon'],
    inclusions: ['4-star accommodations', 'Private transportation', 'Professional guide', 'Most meals', 'Park entrance fees'],
    exclusions: ['International flights', 'Travel insurance', 'Personal expenses', 'Optional activities'],
    created_at: '2024-03-01T00:00:00Z',
    itinerary: sevenDayNamibiaItinerary
  },
  {
    id: '8',
    title: 'Namibia Photography Tour',
    description: 'Capture the incredible landscapes of Namibia with our specialized photography tour, led by professional photographers.',
    price: 2399,
    duration: 12,
    image: '/images/namibia-photography.jpg',
    featured: false,
    attractions: ['Sossusvlei', 'Kolmanskop Ghost Town', 'Quiver Tree Forest', 'Fish River Canyon'],
    inclusions: ['Accommodation', 'Transportation', 'Photography guide', 'Most meals', 'Park entrance fees'],
    exclusions: ['International flights', 'Travel insurance', 'Personal expenses', 'Camera equipment'],
    created_at: '2024-02-25T00:00:00Z',
    itinerary: fourDayNamibiaItinerary
  },
  {
    id: '9',
    title: 'Southern Africa Explorer (Namibia Section)',
    description: 'Experience the incredible landscapes of Southern Africa with this multi-country tour. This package showcases the Namibian portion of the journey.',
    price: 1299,
    duration: 6,
    image: '/images/southern-africa.jpg',
    featured: false,
    attractions: ['Windhoek', 'Kalahari Desert', 'Fish River Canyon', 'Lüderitz'],
    inclusions: ['Accommodation', 'Transportation', 'Guide', 'Most meals', 'Park entrance fees'],
    exclusions: ['International flights', 'Travel insurance', 'Personal expenses', 'Visa fees'],
    created_at: '2024-03-01T00:00:00Z',
    itinerary: southernAfricaTour
  }
];

export const mockVehicles: Vehicle[] = [
  {
    id: '1',
    name: 'Toyota Hilux 4x4',
    type: 'SUV',
    capacity: 4,
    price_per_day: 89,
    image: '/images/toyota-hilux.jpg',
    features: ['4x4 Drive', 'Air Conditioning', 'Roof Tent', 'GPS Navigation', 'Off-road capability'],
    available: true,
    created_at: '2024-01-10T00:00:00Z',
  },
  {
    id: '2',
    name: 'Land Rover Defender',
    type: 'SUV',
    capacity: 6,
    price_per_day: 129,
    image: '/images/land-rover.jpg',
    features: ['4x4 Drive', 'Air Conditioning', 'Roof Rack', 'Off-road capability', 'Extra storage'],
    available: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '3',
    name: 'Toyota Land Cruiser',
    type: 'SUV',
    capacity: 7,
    price_per_day: 149,
    image: '/images/land-cruiser.jpg',
    features: ['4x4 Drive', 'Air Conditioning', 'Roof Tent', 'GPS Navigation', 'Premium Sound System'],
    available: true,
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: '4',
    name: 'Camper Van',
    type: 'Van',
    capacity: 2,
    price_per_day: 109,
    image: '/images/camper-van.jpg',
    features: ['Kitchenette', 'Sleeping Area', 'Solar Power', 'Fridge', 'Outdoor Shower'],
    available: false,
    created_at: '2024-01-25T00:00:00Z',
  },
  {
    id: '5',
    name: 'Nissan X-Trail',
    type: 'SUV',
    capacity: 5,
    price_per_day: 79,
    image: '/images/nissan-xtrail.jpg',
    features: ['Air Conditioning', 'Bluetooth Audio', 'GPS Navigation', 'Cruise Control', 'Fuel Efficient'],
    available: true,
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Family Overland Truck',
    type: 'Truck',
    capacity: 8,
    price_per_day: 199,
    image: '/images/overland-truck.jpg',
    features: ['4x4 Drive', 'Roof Tents', 'Built-in Kitchen', 'Water Storage', 'Solar Power', 'Recovery Equipment'],
    available: true,
    created_at: '2024-02-05T00:00:00Z',
  },
];

// Partner logos for the homepage
export const partnerLogos = [
  {
    src: '/images/partners/namibia-tourism-board.svg',
    alt: 'Namibia Tourism Board',
    url: 'https://namibiatourism.com.na/'
  },
  {
    src: '/images/partners/air-namibia.svg',
    alt: 'Air Namibia',
    url: 'https://www.airnamibia.com/'
  },
  {
    src: '/images/partners/namibia-wildlife-resorts.svg',
    alt: 'Namibia Wildlife Resorts',
    url: 'https://www.nwr.com.na/'
  },
  {
    src: '/images/partners/namibia-travel-association.svg',
    alt: 'Namibia Travel Association',
    url: 'https://www.namibiatourism.com.na/'
  }
];

export const mockReviews: Review[] = [
  {
    id: '1',
    user_id: 'user123',
    tour_package_id: '1',
    vehicle_id: null,
    rating: 5,
    comment: 'The Namibian Highlights Tour was incredible! Our guide was knowledgeable and the accommodations were excellent. Seeing the wildlife in Etosha was a dream come true.',
    user_name: 'Park Jiwon',
    created_at: '2024-02-10T00:00:00Z',
  },
  {
    id: '2',
    user_id: 'user456',
    tour_package_id: '2',
    vehicle_id: null,
    rating: 4,
    comment: 'Great wildlife experience at Etosha. The lodge was beautiful, though the drives were sometimes long. Would definitely recommend for safari lovers!',
    user_name: 'Kim Minjae',
    created_at: '2024-02-12T00:00:00Z',
  },
  {
    id: '3',
    user_id: 'user789',
    tour_package_id: '3',
    vehicle_id: null,
    rating: 5,
    comment: 'The Sossusvlei dunes are absolutely breathtaking! Climbing Big Daddy dune was challenging but worth every step for the view of Deadvlei. Perfect organization by the KoNam team.',
    user_name: 'Lee Hyojin',
    created_at: '2024-02-15T00:00:00Z',
  },
  {
    id: '4',
    user_id: 'user101',
    tour_package_id: null,
    vehicle_id: '1',
    rating: 5,
    comment: 'The Toyota Hilux was perfect for our self-drive adventure. Reliable on all terrains and the roof tent was very comfortable. Will rent again next time!',
    user_name: 'Choi Seungho',
    created_at: '2024-02-18T00:00:00Z',
  },
  {
    id: '5',
    user_id: 'user202',
    tour_package_id: '4',
    vehicle_id: null,
    rating: 4,
    comment: 'The Coastal Adventure was beautiful! Swakopmund is a lovely town and the Skeleton Coast is hauntingly beautiful. Only giving 4 stars because one accommodation wasn\'t as nice as expected.',
    user_name: 'Jung Yoona',
    created_at: '2024-02-20T00:00:00Z',
  },
  {
    id: '6',
    user_id: 'user303',
    tour_package_id: null,
    vehicle_id: '3',
    rating: 5,
    comment: 'The Land Cruiser was spacious and powerful - perfect for our family of 6. Handled the rough roads like a dream and was very comfortable.',
    user_name: 'Kang Jihoon',
    created_at: '2024-02-25T00:00:00Z',
  },
  {
    id: '7',
    user_id: 'user404',
    tour_package_id: '5',
    vehicle_id: null,
    rating: 5,
    comment: 'The Cultural Experience tour was the highlight of our trip to Namibia. Meeting the Himba people was unforgettable and gave us insight into their traditional way of life.',
    user_name: 'Shin Mina',
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: '8',
    user_id: 'user505',
    tour_package_id: '7',
    vehicle_id: null,
    rating: 5,
    comment: 'The 7-day classic tour was perfect! Well-organized itinerary with enough time to enjoy each location. Our guide was excellent and the accommodations were very comfortable.',
    user_name: 'Kim Taehyung',
    created_at: '2024-03-05T00:00:00Z',
  },
];
