[build]
  command = "npm run build:netlify"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_LINT_IGNORE_ERRORS = "1"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_IGNORE_TYPESCRIPT_ERRORS = "1"
  DISABLE_ESLINT = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
